//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace FX.SalesLogix.Modules.GitExtensions.FeedbackService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FeedbackSoap", Namespace="http://www.customerfx.com/webservices/")]
    public partial class Feedback : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SubmitFeedbackOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Feedback() {
            this.Url = global::FX.SalesLogix.Modules.GitExtensions.Properties.Settings.Default.FX_SalesLogix_Modules_GitExtensions_FeedbackService_Feedback;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SubmitFeedbackCompletedEventHandler SubmitFeedbackCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.customerfx.com/webservices/SubmitFeedback", RequestNamespace="http://www.customerfx.com/webservices/", ResponseNamespace="http://www.customerfx.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SubmitFeedback(string FromName, string FromEmail, string FeedbackText) {
            this.Invoke("SubmitFeedback", new object[] {
                        FromName,
                        FromEmail,
                        FeedbackText});
        }
        
        /// <remarks/>
        public void SubmitFeedbackAsync(string FromName, string FromEmail, string FeedbackText) {
            this.SubmitFeedbackAsync(FromName, FromEmail, FeedbackText, null);
        }
        
        /// <remarks/>
        public void SubmitFeedbackAsync(string FromName, string FromEmail, string FeedbackText, object userState) {
            if ((this.SubmitFeedbackOperationCompleted == null)) {
                this.SubmitFeedbackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitFeedbackOperationCompleted);
            }
            this.InvokeAsync("SubmitFeedback", new object[] {
                        FromName,
                        FromEmail,
                        FeedbackText}, this.SubmitFeedbackOperationCompleted, userState);
        }
        
        private void OnSubmitFeedbackOperationCompleted(object arg) {
            if ((this.SubmitFeedbackCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitFeedbackCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SubmitFeedbackCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591