//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FX.SalesLogix.Modules.GitExtensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GitExtensionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GitExtensionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FX.SalesLogix.Modules.GitExtensions.GitExtensionResources", typeof(GitExtensionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AboutImage {
            get {
                object obj = ResourceManager.GetObject("AboutImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Git Extensions for SalesLogix.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Git Extensions for SalesLogix.
        /// </summary>
        internal static string AboutTooltip {
            get {
                return ResourceManager.GetString("AboutTooltip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap AddImage {
            get {
                object obj = ResourceManager.GetObject("AddImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files.
        /// </summary>
        internal static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files to Repository.
        /// </summary>
        internal static string AddTooltip {
            get {
                return ResourceManager.GetString("AddTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Branch.
        /// </summary>
        internal static string BranchText {
            get {
                return ResourceManager.GetString("BranchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Branch.
        /// </summary>
        internal static string BranchTooltip {
            get {
                return ResourceManager.GetString("BranchTooltip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap BrowseImage {
            get {
                object obj = ResourceManager.GetObject("BrowseImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Repository.
        /// </summary>
        internal static string BrowseText {
            get {
                return ResourceManager.GetString("BrowseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Git Repository.
        /// </summary>
        internal static string BrowseTooltip {
            get {
                return ResourceManager.GetString("BrowseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Branch.
        /// </summary>
        internal static string CheckoutText {
            get {
                return ResourceManager.GetString("CheckoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout a Branch.
        /// </summary>
        internal static string CheckoutTooltip {
            get {
                return ResourceManager.GetString("CheckoutTooltip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CommitImage {
            get {
                object obj = ResourceManager.GetObject("CommitImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string CommitText {
            get {
                return ResourceManager.GetString("CommitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit Modified Files.
        /// </summary>
        internal static string CommitTooltip {
            get {
                return ResourceManager.GetString("CommitTooltip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GitExtensionsImage {
            get {
                object obj = ResourceManager.GetObject("GitExtensionsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git Extensions.
        /// </summary>
        internal static string GitExtensionsText {
            get {
                return ResourceManager.GetString("GitExtensionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Git Extensions.
        /// </summary>
        internal static string GitExtensionsTooltip {
            get {
                return ResourceManager.GetString("GitExtensionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Branch.
        /// </summary>
        internal static string MergeText {
            get {
                return ResourceManager.GetString("MergeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge a Branch.
        /// </summary>
        internal static string MergeTooltip {
            get {
                return ResourceManager.GetString("MergeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git Extensions for SalesLogix.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PullImage {
            get {
                object obj = ResourceManager.GetObject("PullImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        internal static string PullText {
            get {
                return ResourceManager.GetString("PullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull From Git Repository.
        /// </summary>
        internal static string PullTooltip {
            get {
                return ResourceManager.GetString("PullTooltip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PushImage {
            get {
                object obj = ResourceManager.GetObject("PushImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        internal static string PushText {
            get {
                return ResourceManager.GetString("PushText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push to Git Repository.
        /// </summary>
        internal static string PushTooltip {
            get {
                return ResourceManager.GetString("PushTooltip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SettingsImage {
            get {
                object obj = ResourceManager.GetObject("SettingsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git Extensions Settings.
        /// </summary>
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Git Extension Settings.
        /// </summary>
        internal static string SettingsTooltip {
            get {
                return ResourceManager.GetString("SettingsTooltip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap StashImage {
            get {
                object obj = ResourceManager.GetObject("StashImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stash Changes.
        /// </summary>
        internal static string StashText {
            get {
                return ResourceManager.GetString("StashText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stash Changes.
        /// </summary>
        internal static string StashTooltip {
            get {
                return ResourceManager.GetString("StashTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Changes.
        /// </summary>
        internal static string ViewChangesText {
            get {
                return ResourceManager.GetString("ViewChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Previous Commits and Changes.
        /// </summary>
        internal static string ViewChangesTooltip {
            get {
                return ResourceManager.GetString("ViewChangesTooltip", resourceCulture);
            }
        }
    }
}
